[workspace]
members = ["macros"]

[package]
name = "strawberry_fields"
version = "0.1.0"
edition = "2021"

[dependencies]
strawberry_fields_macros = {path = "macros", version = "0.1.0"}

[dev-dependencies]
trybuild = "1.0.96"


